apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
#  namespace: web-app_namespace
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-app
    spec:
      restartPolicy: Always
      containers:
        - name: web-app-container
          image: simon1405/web-app  # must be in a remote repository to be loaded into a minikube container
#          imagePullPolicy: Never
          ports:
            - containerPort: 8080